DELETE FROM PCALLOCATION;

INSERT INTO PCALLOCATION (PCID) SELECT PCID FROM PC;

UPDATE PCALLOCATION
SET LOCATIONID = (
SELECT  LOCATIONID
FROM LOCATION
INNER JOIN PC
ON LOCATION.ROOMNO = PC.ROOMNO
WHERE LOCATION.ROOMNO = PC.ROOMNO );

UPDATE PCALLOCATION
SET ROOMNAME = (
SELECT ROOMNAME
FROM PC
WHERE PCALLOCATION.PCID = PC.PCID);

UPDATE PCALLOCATION
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.ROOMNO = PCALLOCATION.ROOMNO AND LOCATION.FLOOR = PCALLOCATION.FLOOR AND LOCATION.TYPE = PCALLOCATION.ROOMNAME);

commit;