DELETE FROM PCALLOCATION;

INSERT INTO PCALLOCATION (PCID) SELECT PCID FROM PC;

UPDATE PCALLOCATION
SET LOCATIONID = (
SELECT  LOCATIONID
FROM LOCATION
INNER JOIN PC
ON LOCATION.ROOMNO = PC.ROOMNO
WHERE LOCATION.ROOMNO = PC.ROOMNO );

UPDATE PCALLOCATION
SET ROOMNAME = (
SELECT ROOMNAME
FROM PC
WHERE PCALLOCATION.PCID = PC.PCID);

UPDATE PCALLOCATION
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.ROOMNO = PCALLOCATION.ROOMNO AND LOCATION.FLOOR = PCALLOCATION.FLOOR AND LOCATION.TYPE = PCALLOCATION.ROOMNAME);

commit;

UPDATE EVENTBOOKING
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.BUILDINGNAME = EVENTBOOKING.BUILDING AND LOCATION.ROOMNO = EVENTBOOKING.ROOM);

UPDATE STAFF
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.ROOMNO = STAFF.ROOM);

UPDATE EVENTBOOKING
SET STAFFID = (
SELECT STAFFID 
FROM STAFF
WHERE EVENTBOOKING.ORGANISER = STAFF.NAME);

UPDATE EVENT
SET STAFFID = (
SELECT STAFFID
FROM STAFF 
WHERE EVENT.ORGANISER = STAFF.NAME);

UPDATE BOOKING 
SET LOCATIONID = (
SELECT LOCATIONID
FROM EVENTBOOKING
WHERE EVENTBOOKING.STARTIME = BOOKING.STARTTIME AND EVENTBOOKING.ENDTIME = BOOKING.ENDTIME AND EVENTBOOKING.BOOKINGDATE = BOOKING.BOOKINGDATE);

UPDATE EVENTBOOKING
SET EVENTBOOKINGID = (
SELECT EVENTID
FROM EVENT
WHERE EVENTBOOKING.STAFFID = EVENT.STAFFID AND EVENTBOOKING.PURPOSE = EVENT.EVENTPURPOSE);

UPDATE LOCATION
SET BUILDINGID = (
SELECT BUILDINGID
FROM BUILDING
WHERE LOCATION.BUILDINGNAME = BUILDING.BUILDINGNAME);

SELECT * FROM EQUIPMENTALLOCATION WHERE EQUIPMENTID = null;

DELETE FROM CONFIGURATION;

DELETE FROM NEWPCALLOCATION;

UPDATE PC
SET LOCATIONID = (
SELECT LOCATIONID
FROM PCALLOCATION
WHERE PCALLOCATION.PCID = PC.PCID);

UPDATE NEWPCALLOCATION
SET PCROLE = 'Office'
WHERE PCROLE IS null;

UPDATE NEWPCALLOCATION
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE NEWPCALLOCATION.ROOM = LOCATION.ROOMNO AND NEWPCALLOCATION.ROOMNAME = LOCATION.TYPE);

SELECT TO_CHAR(TO_DATE(TO_CHAR(BOOKINGDATE || ' ' || STARTTIME), 'dd-mm-yy hh24:mi:ss'), 'yyyy-mm-dd hh24:mi:ss') as NEWDATE FROM BOOKING;

DELETE FROM TEMPDATES;

UPDATE EVENTEND BookingNew
SET ENDDATE = (SELECT TO_DATE(TO_CHAR(BOOKINGDATE || ' ' || ENDTIME), 'DD-MON-RR hh24:mi:ss')
               FROM BOOKING BookingOld
               WHERE BookingOld.BOOKINGID = BookingNew.BOOKINGID);
               
UPDATE EVENTSTART BookingNew
SET ENDDATE = (SELECT TO_DATE(TO_CHAR(BOOKINGDATE || ' ' || STARTTIME), 'DD-MON-RR hh24:mi:ss')
               FROM BOOKING BookingOld
               WHERE BookingOld.BOOKINGID = BookingNew.BOOKINGID);

SELECT TO_CHAR(EVENTEND, 'yyyy-mm-dd hh24:mi:ss') as EVENTEND FROM BOOKING;

SELECT TO_CHAR(EVENTSTART, 'dd-mm-rrrr hh24:mi') as EVENTSTART,TO_CHAR(EVENTEND, 'dd-mm-rrrr hh24:mi') as EVENTEND FROM BOOKING;

Insert into BOOKING (LOCATIONID,EVENTID,EVENTSTART,EVENTEND) values (110015,100,to_date('04-OCT-13 12:30:00','yyyy-mm-dd hh24:mi:ss'),to_date('04-OCT-13 13:00:00','yyyy-mm-dd hh24:mi:ss'));

SELECT PCID, COUNT(PCID) 
FROM PCALLOCATION
GROUP BY PCID
HAVING COUNT(PCID) > 1;

DELETE FROM CONFIGURATION;

COMMIT;

SELECT EVENTSTART, EVENTEND FROM BOOKING;

SELECT BOOKINGID, EVENT.EVENTPURPOSE, TO_CHAR(BOOKING.EVENTSTART, 'dd-mm-rrrr hh24:mi') as EVENTSTART,TO_CHAR(BOOKING.EVENTEND, 'dd-mm-rrrr hh24:mi') as EVENTEND, LOCATION.ROOMNO
FROM BOOKING
INNER JOIN LOCATION
ON BOOKING.LOCATIONID = LOCATION.LOCATIONID
INNER JOIN EVENT
ON BOOKING.EVENTID = EVENT.EVENTID
ORDER BY BOOKINGID;

DELETE FROM BOOKING;

SELECT * FROM BOOKING;

UPDATE BOOKING SET EVENTID = 105, EVENTSTART = to_date('04-OCT-13 11:00:00','yyyy-mm-dd hh24:mi:ss'), EVENTEND = to_date('04-OCT-13 12:00:00','yyyy-mm-dd hh24:mi:ss') WHERE BOOKINGID = 800002;

UPDATE BOOKING SET LOCATIONID = (SELECT LOCATIONID FROM LOCATION WHERE ROOMNO = 'A106') WHERE BOOKINGID = 800002;

SELECT COUNT(*) FROM LOCATION WHERE BUILDINGID = (SELECT BUILDINGID FROM BUILDING WHERE BUILDINGNAME = :name);

SELECT SUM(HOMEPHONENO) FROM STAFF;

SELECT MIN(QUANTITY), MAX(QUANTITY) FROM EQUIPMENTALLOCATION;

COMMIT;

INSERT INTO EQUIPMENTALLOCATION (LOCATIONID, EQUIPMENTID, QUANTITY) VALUES (110001, 111005, -52);

SELECT SUM(WORKPHONENO) FROM STAFF;

SELECT SUM(HORSESHOECAPACITY), SUM(ISLANDCAPACITY), SUM(ROWCAPACITY) FROM CONFIGURATION;

SELECT SUM(LENGTH), SUM(WIDTH) FROM LOCATION;

select event.staffid AS ORGANISERID, staff.staffid, staff.name from event inner join staff on event.staffid = staff.staffid;

SELECT EVENT.STAFFID AS EVENTORGANISERID, EVENTPURPOSE, STAFF.STAFFID, STAFF.NAME
FROM EVENT
INNER JOIN STAFF 
ON EVENT.STAFFID = STAFF.STAFFID;

SELECT TO_CHAR(EVENTSTART, 'DD-MON-RR hh24:mi:ss') AS EVENTEND FROM BOOKING;
