DELETE FROM PCALLOCATION;

INSERT INTO PCALLOCATION (PCID) SELECT PCID FROM PC;

UPDATE PCALLOCATION
SET LOCATIONID = (
SELECT  LOCATIONID
FROM LOCATION
INNER JOIN PC
ON LOCATION.ROOMNO = PC.ROOMNO
WHERE LOCATION.ROOMNO = PC.ROOMNO );

UPDATE PCALLOCATION
SET ROOMNAME = (
SELECT ROOMNAME
FROM PC
WHERE PCALLOCATION.PCID = PC.PCID);

UPDATE PCALLOCATION
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.ROOMNO = PCALLOCATION.ROOMNO AND LOCATION.FLOOR = PCALLOCATION.FLOOR AND LOCATION.TYPE = PCALLOCATION.ROOMNAME);

commit;

UPDATE EVENTBOOKING
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.BUILDINGNAME = EVENTBOOKING.BUILDING AND LOCATION.ROOMNO = EVENTBOOKING.ROOM);

UPDATE STAFF
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE LOCATION.ROOMNO = STAFF.ROOM);

UPDATE EVENTBOOKING
SET STAFFID = (
SELECT STAFFID 
FROM STAFF
WHERE EVENTBOOKING.ORGANISER = STAFF.NAME);

UPDATE EVENT
SET STAFFID = (
SELECT STAFFID
FROM STAFF 
WHERE EVENT.ORGANISER = STAFF.NAME);

UPDATE BOOKING 
SET LOCATIONID = (
SELECT LOCATIONID
FROM EVENTBOOKING
WHERE EVENTBOOKING.STARTIME = BOOKING.STARTTIME AND EVENTBOOKING.ENDTIME = BOOKING.ENDTIME AND EVENTBOOKING.BOOKINGDATE = BOOKING.BOOKINGDATE);

UPDATE EVENTBOOKING
SET EVENTBOOKINGID = (
SELECT EVENTID
FROM EVENT
WHERE EVENTBOOKING.STAFFID = EVENT.STAFFID AND EVENTBOOKING.PURPOSE = EVENT.EVENTPURPOSE);

UPDATE LOCATION
SET BUILDINGID = (
SELECT BUILDINGID
FROM BUILDING
WHERE LOCATION.BUILDINGNAME = BUILDING.BUILDINGNAME);

SELECT * FROM EQUIPMENTALLOCATION WHERE EQUIPMENTID = null;

DELETE FROM CONFIGURATION;

DELETE FROM NEWPCALLOCATION;

UPDATE PC
SET LOCATIONID = (
SELECT LOCATIONID
FROM PCALLOCATION
WHERE PCALLOCATION.PCID = PC.PCID);

UPDATE NEWPCALLOCATION
SET PCROLE = 'Office'
WHERE PCROLE IS null;

UPDATE NEWPCALLOCATION
SET LOCATIONID = (
SELECT LOCATIONID
FROM LOCATION
WHERE NEWPCALLOCATION.ROOM = LOCATION.ROOMNO AND NEWPCALLOCATION.ROOMNAME = LOCATION.TYPE);

SELECT TO_CHAR(TO_DATE(TO_CHAR(BOOKINGDATE || ' ' || STARTTIME), 'dd-mm-yy hh24:mi:ss'), 'yyyy-mm-dd hh24:mi:ss') as NEWDATE FROM BOOKING;

DELETE FROM TEMPDATES;

UPDATE TEMPDATES
SET ENDDATE = (SELECT TO_DATE(TO_CHAR(BOOKINGDATE || ' ' || ENDTIME), 'dd-mm-yy hh24:mi:ss')
               FROM BOOKING
               WHERE TEMPDATES.EVENTID = 110015);

SELECT TO_CHAR(EVENTEND, 'yyyy-mm-dd hh24:mi:ss') as EVENTEND FROM BOOKING;

SELECT LOCATIONID, EVENTID, TO_CHAR(EVENTSTART, 'yyyy-mm-dd hh24:mi:ss') as EVENTSTART,TO_CHAR(EVENTEND, 'yyyy-mm-dd hh24:mi:ss') as EVENTEND FROM BOOKING;

Insert into BOOKING (LOCATIONID,EVENTID,EVENTSTART,EVENTEND) values (110015,100,to_date('04-OCT-13 12:30:00','yyyy-mm-dd hh24:mi:ss'),to_date('04-OCT-13 13:00:00','yyyy-mm-dd hh24:mi:ss'));

SELECT PCID, COUNT(PCID) 
FROM PCALLOCATION
GROUP BY PCID
HAVING COUNT(PCID) > 1;